DROP TABLE HAYDAY.PRODUCT;
DROP TABLE HAYDAY.COST;
DROP TABLE HAYDAY.SUPPLY;

-- --------------------------------------------------------------------------
-- --------------------------------------------------------------------------

CREATE TABLE HAYDAY.SUPPLY (
ID SERIAL,
NAME VARCHAR(255),
MASTERSHIP BOOL,
PRIMARY KEY (ID)
);

CREATE TABLE HAYDAY.COST (
ID NUMERIC,
ID_RELATED NUMERIC,
AMOUNT NUMERIC
);

CREATE TABLE HAYDAY.PRODUCT (
ID SERIAL PRIMARY KEY,
NAME VARCHAR(255),
VALUE NUMERIC,
TIME NUMERIC,
ID_SUPPLY SERIAL
);

-- --------------------------------------------------------------------------
-- --------------------------------------------------------------------------

ALTER TABLE HAYDAY.PRODUCT
ADD CONSTRAINT FK_ID_SUPPLY FOREIGN KEY (ID_SUPPLY) REFERENCES HAYDAY.SUPPLY (ID);

-- --------------------------------------------------------------------------
-- --------------------------------------------------------------------------

INSERT INTO HAYDAY.SUPPLY (NAME, MASTERSHIP) values ('Parcela', false);
INSERT INTO HAYDAY.SUPPLY (NAME, MASTERSHIP) values ('Animal', false);
INSERT INTO HAYDAY.SUPPLY (NAME, MASTERSHIP) values ('Panadería', true);
INSERT INTO HAYDAY.SUPPLY (NAME, MASTERSHIP) values ('Moledora', true);
INSERT INTO HAYDAY.SUPPLY (NAME, MASTERSHIP) values ('Lechería', true);
INSERT INTO HAYDAY.SUPPLY (NAME, MASTERSHIP) values ('Azucarera', true);
INSERT INTO HAYDAY.SUPPLY (NAME, MASTERSHIP) values ('Palomitera', true);
INSERT INTO HAYDAY.SUPPLY (NAME, MASTERSHIP) values ('Barbacoa', true);
INSERT INTO HAYDAY.SUPPLY (NAME, MASTERSHIP) values ('Horno de tartas', true);
INSERT INTO HAYDAY.SUPPLY (NAME, MASTERSHIP) values ('Árbol', false);

INSERT INTO HAYDAY.SUPPLY (NAME, MASTERSHIP) values ('Telar', true);
INSERT INTO HAYDAY.SUPPLY (NAME, MASTERSHIP) values ('Arbusto', false);
INSERT INTO HAYDAY.SUPPLY (NAME, MASTERSHIP) values ('Máquina de coser', true);
INSERT INTO HAYDAY.SUPPLY (NAME, MASTERSHIP) values ('Horno de pasteles', true);
INSERT INTO HAYDAY.SUPPLY (NAME, MASTERSHIP) values ('Mina', false);
INSERT INTO HAYDAY.SUPPLY (NAME, MASTERSHIP) values ('Fundición', true);
INSERT INTO HAYDAY.SUPPLY (NAME, MASTERSHIP) values ('Exprimidor', true);
INSERT INTO HAYDAY.SUPPLY (NAME, MASTERSHIP) values ('Pesca', false);
INSERT INTO HAYDAY.SUPPLY (NAME, MASTERSHIP) values ('Taller de cebos', true);
INSERT INTO HAYDAY.SUPPLY (NAME, MASTERSHIP) values ('Heladería', true);

INSERT INTO HAYDAY.SUPPLY (NAME, MASTERSHIP) values ('Telar de redes', true);
INSERT INTO HAYDAY.SUPPLY (NAME, MASTERSHIP) values ('Mermeladera', true);
INSERT INTO HAYDAY.SUPPLY (NAME, MASTERSHIP) values ('Joyería', true);
INSERT INTO HAYDAY.SUPPLY (NAME, MASTERSHIP) values ('Extractor de miel', true);
INSERT INTO HAYDAY.SUPPLY (NAME, MASTERSHIP) values ('Cafetería', true);
INSERT INTO HAYDAY.SUPPLY (NAME, MASTERSHIP) values ('Cocina para sopas', true);
INSERT INTO HAYDAY.SUPPLY (NAME, MASTERSHIP) values ('Máquina de velas', true);
INSERT INTO HAYDAY.SUPPLY (NAME, MASTERSHIP) values ('Floristería', true);
INSERT INTO HAYDAY.SUPPLY (NAME, MASTERSHIP) values ('Máquina de caramelos', true);
INSERT INTO HAYDAY.SUPPLY (NAME, MASTERSHIP) values ('Puesto de salsas', true);

INSERT INTO HAYDAY.SUPPLY (NAME, MASTERSHIP) values ('Puesto de sushi', true);
INSERT INTO HAYDAY.SUPPLY (NAME, MASTERSHIP) values ('Puesto de ensaladas', true);
INSERT INTO HAYDAY.SUPPLY (NAME, MASTERSHIP) values ('Sandwichería', true);
INSERT INTO HAYDAY.SUPPLY (NAME, MASTERSHIP) values ('Licuadora', true);
INSERT INTO HAYDAY.SUPPLY (NAME, MASTERSHIP) values ('Máquina de pasta', true);
INSERT INTO HAYDAY.SUPPLY (NAME, MASTERSHIP) values ('Wok', true);
INSERT INTO HAYDAY.SUPPLY (NAME, MASTERSHIP) values ('Taller de sombreros', true);
INSERT INTO HAYDAY.SUPPLY (NAME, MASTERSHIP) values ('Cocina para pasta', true);
INSERT INTO HAYDAY.SUPPLY (NAME, MASTERSHIP) values ('Puesto de perritos calientes', true);
INSERT INTO HAYDAY.SUPPLY (NAME, MASTERSHIP) values ('Cocina de tacos', true);

INSERT INTO HAYDAY.SUPPLY (NAME, MASTERSHIP) values ('Tetería', true);
INSERT INTO HAYDAY.SUPPLY (NAME, MASTERSHIP) values ('Fondue', true);
INSERT INTO HAYDAY.SUPPLY (NAME, MASTERSHIP) values ('Freiduría', true);


INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Trigo',3.6,2, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Parcela';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Huevo',18,20, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Animal';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Maíz',7.2,5, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Parcela';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Pan',21.4,5, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Panadería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Pienso de gallina',7.2,5, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Moledora';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Soja',10.8,20, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Parcela';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Pienso de vaca',14.4,10, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Moledora';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Leche',32.4,60, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Animal';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Nata',50.4,20, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Lechería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Caña de azúcar',14.4,30, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Parcela';

INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Pan de maíz',72,30, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Panadería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Azúcar moreno',32.4,20, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Azucarera';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Palomitas',32.4,30, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Palomitera';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Zanahoria',7.2,10, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Parcela';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Mantequilla',82.8,30, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Lechería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Tortitas',108,30, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Barbacoa';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Pienso de cerdo',14.4,20, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Moledora';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Beicon',50.4,240, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Animal';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Galleta',104,60, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Panadería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Huevos con beicon',201.6,60, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Barbacoa';

INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Queso',122.4,60, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Lechería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Añil',25.2,120, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Parcela';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Azúcar blanco',50,40, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Azucarera';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Tarta de zanahoria',82.8,60, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Horno de tartas';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Calabaza',32.4,180,ID FROM HAYDAY.SUPPLY WHERE NAME = 'Parcela';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Tarta de calabaza',158,120, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Horno de tartas';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Manzana',39.6,960, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Árbol';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Lana',54,360, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Animal';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Pienso de oveja',14.4,30, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Moledora';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Palomitas de mantequilla',126,60, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Lechería';

INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Jersey',151,120, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Telar';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Algodón',28,150, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Parcela';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Tarta de beicon',219,180, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Horno de tartas';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Almíbar',90,90, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Azucarera';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Tela de algodón',108,30, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Telar';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Hamburguesa',180,120, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Barbacoa';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Magdalena de frambuesa',140,45, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Panadería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Gorro azul de lana',111,60, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Telar';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Frambuesa',46,1080, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Arbusto';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Camisa de algodón',241,45, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Máquina de coser';

INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Jersey azul',208,180, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Telar';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Pastel de zanahoria',165,90, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Horno de pasteles';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Chaparreras de lana',309,90, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Máquina de coser';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Cereza',68,1620, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Árbol';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Pastel de nata',219,180, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Horno de pasteles';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Pastel de bayas',255,60, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Horno de pasteles';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Pastel de queso',284,240, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Horno de pasteles';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Mineral de plata',18,0, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Mina';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Mineral de oro',21,0, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Mina';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Mineral de platino',32,0, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Mina';

INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Lingote de plata',147,480, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Fundición';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Chile',36,240, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Parcela';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Palomitas de chile',122,120, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Palomitera';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Lingote de oro',180,720, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Fundición';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Lingote de platino',205,960, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Fundición';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Vestido violeta',327,135, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Máquina de coser';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Mora',82.8,1448, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Arbusto';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Magdalena de mora',226,45, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Panadería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Zumo de zanahoria',46,30, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Exprimidor';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Filete de pescado',54,0, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Pesca';

INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Hamburguesa de pescado',226,120, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Barbacoa';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Cebo rojo',0,90, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Taller de cebos';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Cebo verde',0,75, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Taller de cebos';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Cebo azul',0,60, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Taller de cebos';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Cebo morado',0,45, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Taller de cebos';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Cebo dorado',0,30, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Taller de cebos';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Tarta de manzana',270,150, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Horno de tartas';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Gratinado de pescado',226,120, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Horno de tartas';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Zumo de manzana',129,120, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Exprimidor';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Helado de vainilla',172,120, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Heladería';

INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Tomate',43.2,360, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Parcela';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Tomates asados',118,90, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Barbacoa';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Zumo de cereza',216,150, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Exprimidor';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Red de pesca',0,240, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Telar de redes';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Red misteriosa',0,180, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Telar de redes';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Zumo de tomate',162,90, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Exprimidor';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Zumo de bayas',205,180, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Exprimidor';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Pienso de cabra',14.4,40, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Moledora';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Leche de cabra',64.8,480, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Animal';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Queso de cabra',162,90, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Lechería';

INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Pizza',190,15, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Panadería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Carbón',10.8,0, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Mina';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Carbón refinado',108,360, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Fundición';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Polo de cereza',352,180, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Heladería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Fresa',50.4,480, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Parcela';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Tarta de feta',223,90, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Horno de tartas';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Mineral de hierro',14.4,0, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Mina';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Lingote de hierro',129,420, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Fundición';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Helado de fresa',331,240, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Heladería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Haz de trigo',50.4,30, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Moledora';

INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Patata',36,220, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Parcela';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Pastel de fresa',316,180, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Horno de pasteles';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Patata asada',298,35, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Barbacoa';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Mermelada de manzana',219,360, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Mermeladera';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Pastel de chocolate',320,120, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Horno de pasteles';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Gratinado de beicon',367,120, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Horno de tartas';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Cacao',86.4,2040, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Árbol';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Mermelada de frambuesa',252,420, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Mermeladera';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Pizza picante',226,15, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Panadería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Mermelada de mora',388,480, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Mermeladera';

INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Pastelitos de patata',309,120, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Horno de pasteles';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Mermelada de cereza',334,420, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Mermeladera';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Pulsera',514,120, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Joyería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Pan de patata',284,45, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Panadería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Gratinado de carne',280,100, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Horno de tartas';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Helado de chocolate',342,150, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Heladería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Panal',68,0, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Arbusto';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Collar',727,180, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Joyería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Miel',154,20, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Extractor de miel';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Palomitas de miel',360,90, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Palomitera';

INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Anillo con diamante',824,240, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Joyería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Pescado y patatas',244,90, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Barbacoa';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Pulsera metálica',658,90, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Joyería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Granos de café',64.8,1440, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Arbusto';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Café expreso',248,5, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Cafetería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Tarta de manzana y miel',482,200, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Horno de pasteles';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Café con leche',219,10, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Cafetería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Palomitas de chocolate',248,150, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Palomitera';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Cola de langosta',201,360, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Pesca';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Trampa de langostas',0,102, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Telar de redes';

INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Pizza de marisco',403,15, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Panadería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Café moca',291,15, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Cafetería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Moca con frambuesa',259,30, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Cafetería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Sopa de langosta',612,150, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Cocina para sopas';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Chocolate caliente',316,25, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Cafetería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Sopa de tomate',478,90, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Cocina para sopas';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Bufanda roja',288,150, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Telar';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Brocheta de langosta',417,40, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Barbacoa';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Cera de abejas',234,45, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Extractor de miel';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Vela de fresa',370,120, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Máquina de velas';

INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Ramo rústico',208.7,45, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Floristería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Sopa de calabaza',392,120, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Cocina para sopas';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Mermelada de fresa',270,450, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Mermeladera';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Pluma de pato',140,180, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Pesca';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Trampa para patos',0,60, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Telar de redes';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Sésamo',18,60, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Parcela';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Helado de sésamo',176,120, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Heladería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Manzana caramelizada',255,120, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Máquina de caramelos';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Almohada',676,180, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Máquina de coser';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Trampa para patos',0,60, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Telar de redes';

INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Caramelos',176,90, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Máquina de caramelos';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Vela de frambuesa',360,105, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Máquina de velas';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Piña',14,30, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Parcela';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Zumo de piña',68,45, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Exprimidor';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Sopa de pescado',298,180, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Cocina para sopas';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Lirios',21,90, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Floristería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Pastel elegante',450,15, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Horno de pasteles';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Salsa de soja',154,180, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Puesto de salsas';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Chocolate',460,1200, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Máquina de caramelos';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Arroz',18,45, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Parcela';

INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Makis',489,60, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Puesto de sushi';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Aceitunas',82,1440, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Árbol';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Piruleta',342,720, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Máquina de caramelos';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Lechuga',32,210, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Parcela';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Ensalada griega',745,90, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Puesto de ensaladas';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Sushi de langosta',637,60, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Puesto de sushi';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Manta',1098,210, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Máquina para coser';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Gominolas',684,1440, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Máquina de caramelos';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Aceite de oliva',277,45, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Puesto de salsas';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Ajo',14,30, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Parcela';

INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Pan de ajo',198,15, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Barbacoa';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Sándwich vegetal',532,40, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Sandwichería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Ensalada con beicon',723,105, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Puesto de ensaladas';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Mayonesa',367,15, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Puesto de salsas';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Latte caramelo',345,15, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Cafetería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Cacahuetes',234,0, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Árbol';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Cacahuetes garrapiñados',468,40, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Máquina de caramelos';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Girasoles',21,90, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Parcela';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Sushi de huevo',550,120, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Puesto de sushi';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Cóctel de marisco',763,120, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Puesto de ensaladas';

INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Batido de bayas',547,75, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Licuadora';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Aperitivo salado',309,45, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Palomitera';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Ramo colorido',338,20, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Floristería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Sándwich de beicon',648,100, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Sandwichería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Bizcocho de piña',259,75, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Horno de pasteles';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Tarta de chocolate',514,75, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Horno de tartas';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Limón',93,1445, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Árbol';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Olivada',468,45, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Puesto de salsas';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Cuajada de limón',378,25, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Puesto de salsas';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Sándwich de huevo',583,80, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Sandwichería';

INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Batido verde',320,45, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Licuadora';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Pasta fresca',43,15, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Máquina de pasta';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Ensalada de pasta',759,150, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Puesto de ensaladas';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Tarta de limón',446,135, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Horno de tartas';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Cebolla',39,300, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Parcela';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Cebolla a la parrilla',190,60, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Barbacoa';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Pastel de limón',896,150, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Horno de pasteles';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Batido de cacahuete',619,100, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Heladería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Salsa de tomate',230,30, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Puesto de salsas';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Tostada con miel',255,60, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Sandwichería';

INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Arroz frito',205,60, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Wok';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Batido de yogur',349,60, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Licuadora';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Sombrero cloché',468,120, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Taller de sombreros';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Pepino',14,35, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Parcela';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Batido de pepino',266,40, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Licuadora';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Naranja',97,1447, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Árbol';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Chal de flores',295,90, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Telar';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Zumo de naranja',234,120, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Exprimidor';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Sándwich de cacahuete y mermelada',601,25, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Sandwichería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Sopa de cebolla',327,150, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Cocina para sopas';

INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Vela de limón',457,135, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Máquina de velas';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Sombrero de copa',619,210, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Taller de sombreros';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Ñoquis',475,80, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Cocina para pasta';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Remolacha',14,40, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Parcela';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Verduras asadas',198,25, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Barbacoa';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Sopa de fideos',432,120, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Cocina para sopas';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Fideos de arroz',100,20, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Máquina de pasta';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Ramo elegante',500,40, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Floristería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Mermelada de naranja',457,510, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Mermeladera';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Sombrero de playa',558,150, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Taller de sombreros';

INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Lasaña vegetal',532,100, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Cocina para pasta';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Pimiento',36,270, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Parcela';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Crudités',266,120, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Puesto de ensaladas';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Perrito caliente',370,30, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Puesto de perritos calientes';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Melocotón',100,1446, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Árbol';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Tarta de melocotón',435,150, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Horno de tartas';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Perrito vegetariano',367,45, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Puesto de perritos calientes';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Maki grande',648,90, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Puesto de sushi';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Ensalada de remolacha',234,45, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Puesto de ensaladas';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Salsa picante',252,20, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Puesto de salsas';

INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Taco',396,45, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Cocina de tacos';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Rollitos de verano',316,60, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Puesto de ensaladas';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Sorbete de naranja',399,210, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Heladería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Perrito de maíz',529,60, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Puesto de perritos calientes';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Sopa de patata',255,150, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Cocina para sopas';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Jengibre',28,150, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Parcela';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Crocante de sésamo',270,60, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Máquina de caramelos';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Taco de pescado',392,90, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Cocina de tacos';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Mermelada de melocotón',464,480, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Mermeladera';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Pasta con langosta',637,120, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Cocina para pasta';

INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Sándwich de pepino',464,35, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Sandwichería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Pescado picante',543,90, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Wok';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Hojas de té',43,390, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Parcela';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Té verde',241,30, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Tetería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Perrito con cebolla',306,75, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Puesto de perritos calientes';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Pimientos rellenos',352,20, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Barbacoa';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Té con leche',190,45, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Tetería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Sopa de pimiento',439,60, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Cocina para sopas';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Fondue de chocolate',626,25, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Fondue';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Peonías',36,240, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Parcela';

INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Quesadilla',241,60, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Cocina de tacos';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Ensalada de frutas',597,120, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Puesto de ensaladas';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Pasta carbonara',410,150, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Cocina para pasta';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Helado de melocotón',450,180, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Heladería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Té con miel',313,40, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Tetería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Brócoli',21,90, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Parcela';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Pasta con brócoli',345,60, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Cocina para pasta';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Ensalada veraniega',554,180, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Puesto de ensaladas';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Uvas',32,180, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Parcela';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Zumo de uva',104,150, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Exprimidor';

INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Sándwich de cebolla y queso',471,90, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Sandwichería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Mermelada de uva',162,390, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Mermeladera';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Menta',32,180, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Parcela';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Helado de menta',288,135, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Heladería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Corona de flores',331,120, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Taller de sombreros';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Té con limón',241,20, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Tetería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Fondue de beicon',597,30, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Fondue';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Fideos con salsa de cacahuete',597,45, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Wok';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Galleta de jengibre',273,30, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Panadería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Nachos',432,75, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Cocina de tacos';

INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Pasta picante',576,90, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Cocina para pasta';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Sopa de brócoli',237,75, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Cocina para sopas';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Patatas con beicon',302,25, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Freiduría';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Batido mixto',504,30, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Licuadora';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Plátano',104,1620, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Árbol';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Café helado de plátano',277,20, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Cafetería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Té de manzana y jengibre',169,30, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Tetería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Té con naranja',255,40, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Tetería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Pastel de frutas',450,180, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Horno de pasteles';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Setas',10,20, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Parcela';

INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Ensalada con setas',216,60, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Puesto de ensaladas';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Salteado de tofu',306,75, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Wok';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Ramo de caramelos',554,20, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Floristería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Berenjena',14,40, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Parcela';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Berenjena asada',324,40, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Barbacoa';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Pan de plátano',424,30, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Panadería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Fondue de queso',493,20, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Fondue';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Empanadas de manzana',295,20, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Freiduría';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Sandía',39,300, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Parcela';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Té helado',252,30, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Tetería';

INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Tostada con queso de cabra',302,50, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Sandwichería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Zumo de sandía',108,60, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Exprimidor';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Ramo delicado',298,30, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Floristería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Batido de sésamo negro',313,45, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Licuadora';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Ciruela',82,1440, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Árbol';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Tortitas de plátano',352,60, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Barbacoa';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Mermelada de ciruela',385,300, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Mermeladera';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Vela floral',442,120, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Máquina de velas';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Rollo de chocolate',604,90, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Horno de pasteles';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Banana split',403,210, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Heladería';

INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Brocheta de pescado',176,30, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Barbacoa';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Té de menta',255,35, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Tetería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Colgante floral',698,60, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Joyería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Chiles fritos',406,40, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Freiduría';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Pastel de berenjena',442,45, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Horno de tartas';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Batido de cacao',511,40, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Licuadora';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Chocolatinas fritas',658,18, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Freiduría';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Pasta con setas',280,75, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Cocina para pasta';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Batido de ciruela',522,35, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Licuadora';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Sopa de setas',176,80, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Cocina para sopas';

INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Ramo de verduras',352,15, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Floristería';
INSERT INTO HAYDAY.PRODUCT (NAME, VALUE, TIME, ID_SUPPLY) SELECT 'Bolas de arroz',464,45, ID FROM HAYDAY.SUPPLY WHERE NAME = 'Puesto de sushi';

-- --------------------------------------------------------------------------
-- --------------------------------------------------------------------------

insert into HAYDAY.cost (id, id_related, amount) 
select id, (select id from hayday.product where name = 'Pienso de gallina'), 1 from hayday.product where name = 'Huevo';
insert into HAYDAY.cost (id, id_related, amount) 
select id, (select id from hayday.product where name = 'Trigo'), 3 from hayday.product where name = 'Pan';
insert into HAYDAY.cost (id, id_related, amount) 
select id, (select id from hayday.product where name = 'Maíz'), 1 from hayday.product where name = 'Pienso de gallina';
insert into HAYDAY.cost (id, id_related, amount) 
select id, (select id from hayday.product where name = 'Trigo'), 2 from hayday.product where name = 'Pienso de gallina';
insert into HAYDAY.cost (id, id_related, amount) 
select id, (select id from hayday.product where name = 'Maíz'), 1 from hayday.product where name = 'Pienso de vaca';
insert into HAYDAY.cost (id, id_related, amount) 
select id, (select id from hayday.product where name = 'Soja'), 2 from hayday.product where name = 'Pienso de vaca';
insert into HAYDAY.cost (id, id_related, amount) 
select id, (select id from hayday.product where name = 'Pienso de vaca'), 1 from hayday.product where name = 'Leche';
insert into HAYDAY.cost (id, id_related, amount) 
select id, (select id from hayday.product where name = 'Leche'), 1 from hayday.product where name = 'Nata';
insert into HAYDAY.cost (id, id_related, amount) 
select id, (select id from hayday.product where name = 'Maíz'), 2 from hayday.product where name = 'Pan de maíz';
insert into HAYDAY.cost (id, id_related, amount) 
select id, (select id from hayday.product where name = 'Huevo'), 2 from hayday.product where name = 'Pan de maíz';
insert into HAYDAY.cost (id, id_related, amount) 
select id, (select id from hayday.product where name = 'Caña de azúcar'), 1 from hayday.product where name = 'Azúcar moreno';